Document: ibus-gjs
Title: Debian ibus-gjs Manual
Author: <insert document author here>
Abstract: This manual describes what ibus-gjs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ibus-gjs/ibus-gjs.sgml.gz

Format: postscript
Files: /usr/share/doc/ibus-gjs/ibus-gjs.ps.gz

Format: text
Files: /usr/share/doc/ibus-gjs/ibus-gjs.text.gz

Format: HTML
Index: /usr/share/doc/ibus-gjs/html/index.html
Files: /usr/share/doc/ibus-gjs/html/*.html
